config/routes.rb
Bookshare::Application.routes.draw do
  resources :requests

  match 'requests/new/:id' => 'requests#new', :as => :new_request_id
  match 'requests/:id/approve' => 'requests#approve', :as => :request_approve

  resources :locations
  devise_for :users
  
  match 'users/borrowing' => 'users#borrowing', :as => :users_borrowing
  match 'users/borrowed' => 'users#borrowed', :as => :users_borrowed
  resources :users

  resources :books

  root :to => "books#index"

  match 'books/:id/borrow' => 'books#borrow', :as => :borrow_book

  match 'books/:id/return' => 'books#return', :as => :return_book
  match 'about' => 'books#about', :as => :about

end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :book
  belongs_to :user

  after_create :book_request_true
  after_create :set_owner_id_from_book
  before_destroy :book_request_false

  def set_owner_id_from_book
    self.owner_id = self.book.user.id
  end

  def book_request_true
    self.book.request true
  end

  def book_request_false
    self.book.request false
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  load_and_authorize_resource 

  # GET /requests
  # GET /requests.xml
  def index
    @requests = Request.where(:user_id => current_user.id)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @requests }
    end
  end

  # GET /requests/1
  # GET /requests/1.xml
  def show
    @request = Request.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @request }
    end
  end

  # GET /requests/new
  # GET /requests/new.xml
  def new
    @book = Book.find(params[:id])
    @request = Request.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @request }
    end
  end

  # GET /requests/1/edit
  def edit
    @request = Request.find(params[:id])
    @book = Book.find(@request.book)
  end

  # POST /requests
  # POST /requests.xml
  def create
    @request = Request.new(params[:request])

    @borrower = current_user
    UserMailer.request_book_confirmation(@request.book, @borrower).deliver

    respond_to do |format|
      if @request.save
        format.html { redirect_to(@request.book, :notice => 'Request was successfully created.') }
        format.xml  { render :xml => @request, :status => :created, :location => @request }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @request.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /requests/1
  # PUT /requests/1.xml
  def update
    @request = Request.find(params[:id])

    respond_to do |format|
      if @request.update_attributes(params[:request])
        format.html { redirect_to(@request, :notice => 'Request was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @request.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.xml
  def destroy
    @request = Request.find(params[:id])
    @request.destroy

    respond_to do |format|
      format.html { redirect_to(requests_url) }
      format.xml  { head :ok }
    end
  end

  def approve
    @request = Request.find(params[:id])
    book = @request.book
    book.borrower_user_id = @request.user.id
    book.save

    @request.destroy

    redirect_to requests_path, :notice => 'Book has been approved'
  end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.haml
= form_for(@request) do |f|
  - if @request.errors.any?
    #error_explanation
      %h2
        = pluralize(@request.errors.count, "error")
        prohibited this request from being saved:
      %ul
        - @request.errors.full_messages.each do |msg|
          %li= msg
  .field
    = render @book
    = f.hidden_field :book_id, :value => @book.id
  #message.field
    = f.label :message
    %br/
    = f.text_area :message, :rows => 10
  .field
    = f.hidden_field :user_id, :value => current_user.id
  .actions
    = f.submit
  %div{:style => "clear: both"}/

app/views/requests/edit.html.haml
%h1 Editing request
= render 'form'
= link_to 'Show', @request
|
= link_to 'Back', requests_path

app/views/requests/index.html.haml
%h1 You are asking to borrow:
- @requests.each do |request|
  .request
    %span.title= link_to request.book.title, request.book
    %br/
    %span.name
      from #{request.book.user.name}
    = link_to 'Remove Request', request, :confirm => 'Are you sure?', :method => :delete
%br/
%h1 Books that others want to borrow:
- current_user.my_requested.each do |request|
  .request
    = request.user.name
    wants to borrow
    %br/
    %span.title= link_to request.book.title, request.book
    %br/
    %h3 Message:
    .message
      = request.message
    = link_to 'Approve Request', request_approve_path(request)
    = link_to 'Remove Request', request, :confirm => 'Are you sure?', :method => :delete

app/views/requests/new.html.haml
.request_new
  %div
    You are requesting:
  #title
    = @book.title
    %br/
  #name
    from #{@book.user.name}
  %br/
  = render 'form'
  = link_to 'Back', requests_path

app/views/requests/show.html.haml
%p#notice= notice
%p
  %b Book:
  = @request.book_id
%p
  %b User:
  = @request.user_id
= link_to 'Edit', edit_request_path(@request)
|
= link_to 'Back', requests_path