config/routes.rb
Bookshare::Application.routes.draw do
  resources :requests

  match 'requests/new/:id' => 'requests#new', :as => :new_request_id
  match 'requests/:id/approve' => 'requests#approve', :as => :request_approve

  resources :locations
  devise_for :users
  
  match 'users/borrowing' => 'users#borrowing', :as => :users_borrowing
  match 'users/borrowed' => 'users#borrowed', :as => :users_borrowed
  resources :users

  resources :books

  root :to => "books#index"

  match 'books/:id/borrow' => 'books#borrow', :as => :borrow_book

  match 'books/:id/return' => 'books#return', :as => :return_book
  match 'about' => 'books#about', :as => :about

end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :location
  belongs_to :user
  has_many :requests

  validates :location_id, :title, :user_id, :isbn, :presence => true
  
  def self.new_from_isbn_or_upc(input)
    Book.new(LookupService.find_attributes_by_isbn_or_upc(input))
  end

  def request(status)
    self.requested = status
    save
  end

  def borrowed?
    !self.borrower_user_id.nil?
  end

  def borrow_status
    if borrowed?
      b_user = User.find(self.borrower_user_id)
      return "#{b_user.first_name} #{b_user.last_name} is borrowing this book." 
    end
    ""
  end

  def book_status_css
    if !self.borrower_user_id.nil?
      return "borrowed"
    elsif self.requested?
      return "requested"
    end
    ""
  end

  def in_public_location?
    self.location.public?
  end

  def borrower
    User.find(self.borrower_user_id) if self.borrower_user_id
  end

  # TODO remove this
  def borrower_email
    borrower.email
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  include BooksHelper

  load_and_authorize_resource

  # GET /books
  # GET /books.xml
  def index
    #@books = Book.all
    if user_signed_in?
      @locations = Location.where(:user_id => current_user.id)
      @locations = @locations + Location.where("user_id <> #{current_user.id}")
    else
      @locations = Location.all
    end
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @books }
    end
  end

  # GET /books/1
  # GET /books/1.xml
  def show
    #@book = Book.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @book }
    end
  end

  # GET /books/new
  # GET /books/new.xml
  def new
    #@book = Book.new

    if current_user.locations.count == 0
      redirect_to new_location_path, :notice => "Need to add a location first"
    else

      respond_to do |format|
        format.html # new.html.erb
        format.xml  { render :xml => @book }
      end
    end
  end

  # GET /books/1/edit
  def edit
    #@book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.xml
  def create
    @book = current_user.books.new_from_isbn_or_upc(params[:book][:isbn])
    @book.location = current_user.locations.find params[:book][:location_id]
        
    respond_to do |format|
      if @book.save
        format.html { redirect_to(new_book_path, :notice => "Successfully added #{@book.title}.") }
        format.xml  { render :xml => @book, :status => :created, :location => @book }
      else
        flash[:alert] = "Invalid barcode" 
        format.html { render :action => "new" }
        format.xml  { render :xml => @book.errors, :status => :unprocessable_entity }
      end
    end
  end


  # PUT /books/1
  # PUT /books/1.xml
  def update
    #@book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to(@book, :notice => 'Book was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @book.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.xml
  def destroy
    #@book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to(books_url, :notice => 'Book has been removed') }
      format.xml  { head :ok }
    end
  end

  def borrow
    @book = Book.find(params[:id])

    @book.borrower_user_id = current_user.id
    @book.save

    @borrower = current_user
    UserMailer.borrow_book_confirmation(@book, @borrower).deliver
    
    redirect_to(@book, :notice => 'Book has been borrowed and its owner has been notified.')
  end

  def return
    #@book = Book.find(params[:id])

    @book.borrower_user_id = nil
    @book.save
    UserMailer.return_book_confirmation(@book, current_user).deliver
 
    redirect_to(@book, :notice => 'Book has been returned and owner has been notified')
  end
  
  def about
  end
  
end

app/helpers/books_helper.rb
module BooksHelper


end

#begin
#    upc = ARGV[0]
#    upc = upc.to_s()
#    if upc.length() == 13 && upc[0..2] == "978"
#        puts convert(upc)
#    else
#        puts "UPC length must be 13"
#    end
#rescue
#    puts "Please input UPC"
#end

app/views/books/_book.html.haml
.book_wrapper
  .book{ :class => book.book_status_css }
    = link_to image_tag(book.image_url, :title => book.borrow_status), book

    %p.title
      = book.title

    - if book.borrowed? && can?(:borrow, Book) && book.borrower.id == current_user.id
      .return_link
        = link_to "Return book", return_book_path(book)

app/views/books/_form.html.haml
= form_for(@book) do |f|
  - if @book.errors.any?
    #error_explanation
      %h2
        = pluralize(@book.errors.count, "error")
        prohibited this book from being saved:
      %ul
        - @book.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :title
    %br/
    = f.text_field :title
  .field
    = f.label :user_id
    %br/
    = f.collection_select :user_id, User.all, :id, :email
  .field
    = f.label :location
    %br/
    = f.collection_select :location_id, Location.all, :id, :name
  .field
    = f.label :isbn
    %br/
    = f.text_field :isbn
  .actions
    = f.submit

app/views/books/_form.new.html.haml
= form_for(@book) do |f|
  - if @book.errors.any?
    #error_explanation
      %h2
        = pluralize(@book.errors.count, "error")
        prohibited this book from being saved:
      %ul
        - @book.errors.full_messages.each do |msg|
          %li= msg
  %br/
  .field
    = f.label "ISBN or UPC"
    %br/
    = f.text_field :isbn
  %br/
  .field
    = f.label :location
    %br/
    = f.collection_select :location_id, current_user.locations.all, :id, :name
  .field
    - if user_signed_in?
      = f.hidden_field :user_id, :value => current_user.id
  %br/
  .actions
    = f.submit
%script{:language => "javascript", :type => "text/javascript"}
  document.getElementById('book_isbn').focus()

app/views/books/_index.html.haml
- @locations.each do |location| 
  .location
    %br
    %h1
      %b
        = link_to location.name, "/locations/#{location.id}"

    %br
    = render location.books 

app/views/books/about.html.haml
%b
  About us:
%br
%br

= link_to image_tag("http://farm5.static.flickr.com/4126/5193351501_851e2b1649_z.jpg", :width=>"640", :height=>"349", :alt=>"DSC_0022"), "http://www.flickr.com/photos/baltimorehackathon/5193351501/"

%br 
%br 

%b
  Developers:   Eric Oestrich, Patricia Gorla, Paul Kauders
  %br
  %br

%p
  Contributors:   Jason Denney, Michael Rosner, Jonathan Julian, Scott Messenger, and the Baltimore Hackathon!

%br
%p{ :style => "margin-bottom: 15px;" }
  Visit us on 
  = link_to "github", "http://github.com/oestrich/bookshare"

app/views/books/edit.html.haml
%h1
  Editing book

= render 'form'

= link_to 'Show', @book
|
= link_to 'Back', books_path 

app/views/books/index.html.haml
.new
  - if can? :create, Book
    = link_to 'New Book', new_book_path
  - if can? :create, Location
    = link_to "New Location", new_location_path 

= render 'index'

%br

app/views/books/new.html.haml
%b New book
= render 'form.new'

%br/
= link_to 'Back', books_path
- @locations = Location.all

%br/
%br/
= render 'index'

app/views/books/show.html.haml
/ <p id="notice"><haml:loud> notice </haml:loud></p>
%p.details
  %b= @book.title
  by
  \#{@book.author}
%p.details
  %b Owner:
  = @book.user.email
%p.details
  %b Borrower:
  - if can? :borrow, Book
    - if @book.borrowed?
      = @book.borrower_email
    - elsif !@book.in_public_location? && @book.requested?
      = "Requested"
    - elsif !@book.in_public_location?
      = link_to 'Request this book', new_request_id_path(@book)
    - else
      = link_to 'Borrow', borrow_book_path(@book)
  - else
    = link_to 'Signup', new_user_registration_path()
    or #{link_to 'Sign in', new_user_session_path} to borrow!
%p.details
  %b Location:
  = @book.location.name
%p.details
  %b Isbn:
  = @book.isbn
%p.details
  %b Lowest Used Price:
  = @book.lowest_used_price
%p.details
  = render @book
  %div{:style => "clear: both;"}/
%p.details
  = link_to "View details & related books on Amazon", @book.details_url, :target => "_blank"
%br/
- if can? :edit, Book
  = link_to 'Edit', edit_book_path(@book)
  |
- if can? :return, Book
  - if @book.borrower_user_id == current_user.id
    = link_to 'Return', return_book_path(@book)
    |
  - elsif !@book.location.public && !@book.requested?
    = link_to 'Request this book', new_request_id_path(@book)
    |
  - elsif @book.borrower_user_id == nil
    = link_to 'Borrow', borrow_book_path(@book)
    |
- if can? :destroy, Book
  - if @book.user_id == current_user.id
    = link_to 'Destroy', @book, :confirm => 'Are you sure?', :method => :delete
    |
= link_to 'Back', books_path