config/routes.rb
Bookshare::Application.routes.draw do
  resources :requests

  match 'requests/new/:id' => 'requests#new', :as => :new_request_id
  match 'requests/:id/approve' => 'requests#approve', :as => :request_approve

  resources :locations
  devise_for :users
  
  match 'users/borrowing' => 'users#borrowing', :as => :users_borrowing
  match 'users/borrowed' => 'users#borrowed', :as => :users_borrowed
  resources :users

  resources :books

  root :to => "books#index"

  match 'books/:id/borrow' => 'books#borrow', :as => :borrow_book

  match 'books/:id/return' => 'books#return', :as => :return_book
  match 'about' => 'books#about', :as => :about

end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :books

  belongs_to :user
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  load_and_authorize_resource

  # GET /locations
  # GET /locations.xml
  def index
    #@locations = Location.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @locations }
    end
  end

  # GET /locations/1
  # GET /locations/1.xml
  def show
    #@location = Location.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @location }
    end
  end

  # GET /locations/new
  # GET /locations/new.xml
  def new
    #@location = Location.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @location }
    end
  end

  # GET /locations/1/edit
  def edit
    #@location = Location.find(params[:id])
  end

  # POST /locations
  # POST /locations.xml
  def create
    #@location = Location.new(params[:location])

    respond_to do |format|
      if @location.save
        format.html { redirect_to('/', :notice => 'Location was successfully created.') }
        format.xml  { render :xml => @location, :status => :created, :location => @location }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @location.errors, :status => :unprocessable_entity }
        redirect_to "/locations/new"
      end
    end
  end

  # PUT /locations/1
  # PUT /locations/1.xml
  def update
    #@location = Location.find(params[:id])

    respond_to do |format|
      if @location.update_attributes(params[:location])
        format.html { redirect_to(@location, :notice => 'Location was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @location.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.xml
  def destroy
    #@location = Location.find(params[:id])
    @location.destroy

    respond_to do |format|
      format.html { redirect_to(locations_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.haml
= form_for(@location) do |f|
  - if @location.errors.any?
    #error_explanation
      %h2
        = pluralize(@location.errors.count, "error")
        prohibited this location from being saved:
      %ul
        - @location.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :public
    %br/
    = f.radio_button :public, true
    Yes
    \#{f.radio_button :public, false} No
  .field
    = f.hidden_field :user_id, :value => current_user.id
  .actions
    = f.submit

app/views/locations/edit.html.haml
%h1 Editing location
= render 'form'
= link_to 'Show', @location
|
= link_to 'Back', locations_path

app/views/locations/index.html.haml
%b Locations
%br/
%br/
- @locations.each do |location|
  = link_to location.name, location
  %br/
  %br/
%br/

app/views/locations/new.html.haml
%h1
  %b New location
%br/
= render 'form'
%br/
= link_to 'Back', locations_path

app/views/locations/show.html.haml
%p#notice= notice
%p
  %b= @location.name
  - if can? :manage, Location
    = link_to 'Edit', edit_location_path(@location)
- @location.books.each do |book|
  = render book
%div{:style => "clear: both;"}
  = link_to 'Back', locations_path